### ISSUE TITLE
Build error in Kibana

### ISSUE THREAD

**Issue by stacey-gammon** [w33ble/redux-thunks#1]
Including this package, and using it, was causing a build error in Kibana when you run `npm run build` -- `SyntaxError: Unexpected token: punc (.) [kibana.bundle.js:399244,26]`

Though there was no problem when running `npm start`.

I ended up just taking the package out and using the old style syntax so never figured out specifically what the problem was.

**Comment by w33ble** [comment]
I think this is a build problem. I need to add an es5 browser target to get usable output in the build assets.

**Comment by w33ble** [comment]
I just published 0.3.1 with browser support in babel-end, so the build should run in the browser, and thus correctly in webpack. 

@Stacey-Gammon I haven't tested it out yet, but if you have a previously non-working bit of code handy, would you mind upgrading to 0.3.1 and giving it a try?

**Comment by w33ble** [comment]
Since I’ve been building and running this version in Kibana for a while now, I’m calling this issue fixed.
